# -*- coding: utf-8 -*-
"""python1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1znAJf6KZOlMP5QZahibK4h51H2861KV6
"""

import numpy as np
import time

print("hello")

a = np.random.rand(5000000) # makes an array of 500 random integers
b = np.random.rand(5000000) # makes an array of 500 random integers

tic=(time.time())
c = np.dot(a,b)
toc=(time.time())

print(c)
print( "with vectorization: " + str(1000*(toc-tic)) + "ms")

tic=(time.time())
for i in range (1,5000000):
  c = a[i]*b[i]
toc=(time.time())
print( "without vectorization: " + str(1000*(toc-tic)) + "ms")

# Broadcasting, transposing  demo
# VARIATION 1
import numpy

# SITUATION
# each column represents a food type.
# each row represents calories from carbs, proteins and fats.
# QUESTION
# for each food item, calculate the percentage of carb calories.

a = numpy.array(
    [
       [56.0, 0.0, 4.4, 68.0],
       [1.2, 104.0, 52.0, 8.0],
       [0.0, 100.0, 23.2, 4.2]
    ]
)

calc = numpy.sum(a, axis=0)
print(calc)

ans = 100 * (a[0] / calc)
print(ans)

